### ISSUE TITLE
Link to "How to compile and run a simple MS-MPI program" is broken

### ISSUE THREAD

**Issue by MikeHeiber** [microsoft/Microsoft-MPI#10]
Did this article get moved to a new url?  It was a very useful tutorial example.

**Comment by jithinjosepkl** [comment]
Not sure if it was moved - Are you referring to this one - [How to compile and run a simple MS-MPI program](https://blogs.technet.microsoft.com/windowshpc/2015/02/02/how-to-compile-and-run-a-simple-ms-mpi-program/)

**Comment by MikeHeiber** [comment]
Yes, and the link now appears to be working correctly on the README.
