### ISSUE TITLE
Which version of the MPI standard is made available?

### ISSUE THREAD

**Issue by jansende** [microsoft/Microsoft-MPI#16]
Maybe the information is buried somewhere, but I couldn't find it... Anyways, there should be a small notice on the main page, which says what version of the MPI standard can be used with this implementation!

**Comment by hpourreza** [comment]
The [README](https://github.com/microsoft/Microsoft-MPI/blob/master/README.md) file says which version of MPI is supported by MSMPI. It is 2.2 with some features from 3.1.
