### ISSUE TITLE
[VERSION] Microsoft-MPI

### ISSUE THREAD

**Issue by Voskrese** [microsoft/Microsoft-MPI#43]
https://www.nuget.org/packages/msmpisdk/
MSMPIsdk 10.1.12498.18

```
10.1.12498.18 | 3 581 | 8 months ago

10.1.12498.16 | 235 | 10 months ago
```

https://github.com/microsoft/Microsoft-MPI/blob/master/src/mpi.props

```
      <ProductMajorVersion>10</ProductMajorVersion>
      <ProductMinorVersion>1</ProductMinorVersion>
      <BuildMajorVersion>12498</BuildMajorVersion>
      <BuildMinorVersion>16</BuildMinorVersion>
```

/cc @jithinjosepkl
could you update the version of files in the repository to the new version

**Comment by jithinjosepkl** [comment]
@Voskrese , sure we will update this in the next release. But please note that there are no source code changes between these two versions (only difference is in the signing configuration).

**Comment by Voskrese** [comment]
ok
