### ISSUE TITLE
Conda Recipe?

### ISSUE THREAD

**Issue by RyanMcCarthy-NOAA** [microsoft/Microsoft-MPI#50]
Have you attempted to create a conda package for msmpi? I wanted to double check before trying to add a [recipe](https://conda-forge.org/#add_recipe) myself.

**Comment by RyanMcCarthy-NOAA** [comment]
I started working on a [conda recipe](https://github.com/conda-forge/staged-recipes/pull/12751), but I'm getting build errors about [missing headers](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=215347&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77) (`excpt.h` and `stdint.h`). Any tips on resolving these errors?

**Comment by leofang** [comment]
I think this can be closed now? :)
