### ISSUE TITLE
MS-MPI download links for 10.1.1/10.1.2 in Microsoft Download Center are dead

### ISSUE THREAD

**Issue by leofang** [microsoft/Microsoft-MPI#54]
Not sure what's the proper channel to communicate this problem. Because there is no contact info on the website, I'm opening an issue here.

The download links to MS-MPI 10.1.1 and 10.1.2 on the official [Release Notes](https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi-release-notes) are invalid. It now says "We're sorry, this download is no longer available." Please fix it, thank you.

ps. The link to 10.0 is still alive.

**Comment by KineticTheory** [comment]
I am seeing the same problem.  As a work around, [winget](https://github.com/microsoft/winget-cli) still reports the correct download URL and can install version 10.1.2.

```console
c:\temp> winget install microsoft.msmpi
Found Microsoft MPI [microsoft.msmpi]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe
```

**Comment by leofang** [comment]
Thanks, @KineticTheory! I am not a Windows user so this is my first time to learn winget. I raise this issue because I am a maintainer of the msmpi-feedstock and mpi4py.

Currently, [mpi4py keeps track of all past MS-MPI links](https://github.com/mpi4py/mpi4py/blob/18f16da45eaaacfba4cc0293964e1a6548d4c6a6/.azure/install-msmpi.ps1#L6-L17). So the link reported by winget is just for the MS-MPI Runtime, and for completeness I am posting the links below:
10.1.2:
- SDK: https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi
- Runtime: https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe

10.1.1:
- SDK:

**Comment by leofang** [comment]
Looks like it's fixed!

10.1.1: https://www.microsoft.com/en-us/download/details.aspx?id=100305
10.1.2: https://www.microsoft.com/en-us/download/details.aspx?id=100593

**Comment by BERHANU731** [comment]
how to download MPI to my Machine ?
